### ISSUE TITLE
google-services.json is missing.

### ISSUE THREAD

**Issue by baabar69-zz** [potato16/todog#1]
flutter run
Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Initializing gradle...                                              2.0s
Resolving dependencies...                                          13.2s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
                                                                        
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\HP\Desktop\todog-master\android\app\src\nullnull\debug\google-services.json
  C:\Users\HP\Desktop\todog-master\android\app\src\debug\nullnull\google-services.json
  C:\Users\HP\Desktop\todog-master\android\app\src\nullnull\google-services.json
  C:\Users\HP\Desktop\todog-master\android\app\src\debug\google-services.json
  C:\Users\HP\Desktop\todog-master\android\app\src\nullnullDebug\google-services.json
  C:\Users\HP\Desktop\todog-master\android\app\google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        41.3s
Gradle task assembleDebug failed with exit code 1

**Comment by potato16** [comment]
Please follow this link to create your own firebase and get google-service json from there: https://firebase.google.com/docs/android/setup

**Comment by potato16** [comment]
Please set-up your own firebase project and get google service json file from there.
https://codelabs.developers.google.com/codelabs/flutter-firebase/#5
